import {ReactNode} from "react";
import type {Metadata} from "next";
import '@/styles/globals.scss';
import '@/styles/mario.scss';
import {Geist, Geist_Mono} from "next/font/google";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter';
import NavBar from "@/components/navbar";
import {ThemeProvider} from '@mui/material/styles';
import theme from '@/theme';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
	                                   children,
}: Readonly<{
	children: ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased root-page`}
        >
          <AppRouterCacheProvider>
            <NavBar />
            {children}
          </AppRouterCacheProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
